### ISSUE TITLE
CORS policy: No 'Access-Control-Allow-Origin' header is present error

### ISSUE THREAD

**Issue by chdaesung** [xenova/doodle-dash#1]
I tested the codes given on your blog https://huggingface.co/blog/ml-web-games but have got the following error from the browser console.
```
Access to fetch at 'https://hf.co/datasets/huggingface/documentation-images/resolve/main/blog/ml-web-games/skateboard.png' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
localhost/:1 Access to fetch at 'https://hf.co/datasets/huggingface/documentation-images/resolve/main/blog/ml-web-games/skateboard.png' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
hub.js:206        Uncaught TypeError: Failed to fetch
    at getFile (hub.js:206:16)
    at _RawImage.fromURL (image.js:124:30)
    at _RawImage.read (image.js:111:31)
    at worker.js?type=module&worker_file:10:30
```
The error looks like an CORS issue but I could not find how you handled CORS issue in the source codes on  https://github.com/xenova/doodle-dash. 
Help me how to solve the error.

**Comment by xenova** [comment]
"hf.co" should be "huggingface.co", my bad! I'll get that fixed.

Thanks for pointing it out!

**Comment by xenova** [comment]
Fixed now! Thanks again 🤗
